Type size_t is defined in stddef.h
wooorm/levenshtein.c pull request #9
Opened 2022-09-07 17:53 UTC by msteinert

Without this include:

    $ cat main.c
    #include "levenshtein.h"

    int main(void)
    {
	    return 0;
    }
    $ gcc main.c
    In file included from main.c:1:
    levenshtein.h:16:1: error: unknown type name ‘size_t’
       16 | size_t
	  | ^~~~~~
    levenshtein.h:1:1: note: ‘size_t’ is defined in header ‘<stddef.h>’; did
    you forget to ‘#include <stddef.h>’?
      +++ |+#include <stddef.h>
	1 | #ifndef LEVENSHTEIN_H
    levenshtein.h:19:1: error: unknown type name ‘size_t’
       19 | size_t
	  | ^~~~~~
    levenshtein.h:19:1: note: ‘size_t’ is defined in header ‘<stddef.h>’;
    did you forget to ‘#include <stddef.h>’?
    levenshtein.h:20:37: error: unknown type name ‘size_t’
       20 | levenshtein_n (const char *a, const size_t length, const char
    *b, const size_t bLength);
	  |                                     ^~~~~~
    levenshtein.h:20:73: error: unknown type name ‘size_t’
       20 | levenshtein_n (const char *a, const size_t length, const char
    *b, const size_t bLength);
	  |
    ^~~~~~

2022-09-07 17:54 UTC, msteinert commented
For further reference: https://en.cppreference.com/w/c/types/size_t

2022-09-07 19:11 UTC, wooorm commented
Hey! I’m not good at C, at all. How come nobody recognized this before? I’m guessing everyone has included that themselves already?

As you’re linking to `cppreference`, it sounds like C++-specific docs, rather than C-specific docs. 🤔

2022-09-07 19:47 UTC, msteinert commented
https://cppreference.com also has excellent C documentation. Probably because C++ has C interop? Have a look at the main page, you'll see there is a section for ever major revision of C since C89.

Likely people have done this in the past:

```
#include <stddef.h>  // or one of many other headers that define size_t
#include <levenshtein.h>
```

If you're unsure, copy the example I put in the commit message and try it yourself.

2022-09-07 20:09 UTC, msteinert commented
Here is the draft of the final revision of C99 (the published standard requires payment): https://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf

Check out section 7.17.

2022-09-07 23:55 UTC, dcousens commented
@wooorm it's probably because including __almost any C standard header__ will transitively include `stddef`.
I don't think many users will have manually written `#include <stddef.h>`, because many users probably have at least some kind of IO, for example `stdio.h`, within their program.

2022-09-07 23:59 UTC, dcousens requested changes
@msteinert could remove `#include <stdint.h>` https://github.com/wooorm/levenshtein.c/blob/8d254cb3a77fa7bceb6638b57b85d2d51de75a4a/levenshtein.c#L7

2022-09-08 01:16 UTC, msteinert commented
`SIZE_MAX` is defined in `stdint.h`.

```
$ make
cc levenshtein.c -D_GNU_SOURCE -std=c99 -Wall -Wno-format-y2k -W -Wstrict-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wbad-function-cast -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -c -o levenshtein.o
levenshtein.c: In function ‘levenshtein_n’:
levenshtein.c:44:13: error: ‘SIZE_MAX’ undeclared (first use in this function)
   44 |     index = SIZE_MAX;
      |             ^~~~~~~~
levenshtein.c:8:1: note: ‘SIZE_MAX’ is defined in header ‘<stdint.h>’; did you forget to ‘#include <stdint.h>’?
    7 | #include "levenshtein.h"
  +++ |+#include <stdint.h>
    8 | 
levenshtein.c:44:13: note: each undeclared identifier is reported only once for each function it appears in
   44 |     index = SIZE_MAX;
      |             ^~~~~~~~
```

2022-09-08 05:15 UTC, dcousens approved these changes
LGTM

2022-09-08 17:10 UTC, wooorm approved these changes

2022-09-08 17:11 UTC, merged

2022-09-08 17:18 UTC, wooorm commented
thanks, tagged as [2.0.2](https://github.com/wooorm/levenshtein.c/releases/tag/2.0.2)!